#!/usr/bin/env bash
set -Eeuo pipefail
cd "$(dirname "$0")/.."

if [[ ! -f .env ]]; then
  cp .env.example .env
fi

# Reuse the token generated by the adjacent MCP gateway repo when available.
if [[ -f ../mcp-gateway/.env ]]; then
  token="$(grep -E '^MCP_GATEWAY_AUTH_TOKEN=' ../mcp-gateway/.env | tail -1 | cut -d= -f2- || true)"
  if [[ -n "$token" ]]; then
    python3 - "$token" <<'PY'
import pathlib, sys
p = pathlib.Path('.env')
token = sys.argv[1]
lines = p.read_text().splitlines() if p.exists() else []
out=[]
seen=False
for line in lines:
    if line.startswith('MCP_GATEWAY_AUTH_TOKEN='):
        out.append('MCP_GATEWAY_AUTH_TOKEN=' + token)
        seen=True
    else:
        out.append(line)
if not seen:
    out.append('MCP_GATEWAY_AUTH_TOKEN=' + token)
p.write_text('\n'.join(out) + '\n')
PY
    echo "Imported MCP gateway token from ../mcp-gateway/.env"
  fi
fi

if ! docker network inspect ai-local >/dev/null 2>&1; then
  docker network create ai-local >/dev/null
  echo "Created Docker network: ai-local"
fi

./scripts/configure-ollama-64k.sh

docker compose up -d --build

echo
echo "Pi Web UI: http://127.0.0.1:${PI_WEB_PORT:-8787}"
echo "Ollama:    existing server at http://127.0.0.1:11434"
echo "MCP:       mcp-gateway over ai-local"
echo
echo "Use ./scripts/status.sh to verify connectivity."
